language: node_js
node_js: stable
branches:
  only:
    - master
install:
  - npm install
script:
  - ALGOLIA_ADMIN_KEY=$ALGOLIA_ADMIN_KEY ALGOLIA=true npm run build
deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  keep-history: true
  local_dir: public
  on:
    branch: master
